import { create } from "zustand";

export const useToolStore = create((set) => ({
  tool: "select",
  color: "#ffffff",
  strokeWidth: 3,
  lineType: "solid",
  endType: "none",
  startCap: "none",
  endCap: "none",
  opacity: 100,
  startSize: 5,
  endSize: 6,
  lineBezier: false,
  filled: true,
  fontSize: 10,
  textStyle: 0,
  textAlign: "center",
  iconId: "check",
  iconLabel: "",
  hllId: "garrison",
  hllShowRadius: true,
  hllRadiusCheck: true,
  setTool: (tool) => set({ tool }),
  setColor: (color) => set({ color }),
  setStrokeWidth: (strokeWidth) => set({ strokeWidth }),
  setLineType: (lineType) => set({ lineType }),
  setEndType: (endType) => set({ endType }),
  setFilled: (filled) => set({ filled }),
  setFontSize: (fontSize) => set({ fontSize }),
  setTextStyle: (textStyle) => set({ textStyle }),
  setTextAlign: (textAlign) => set({ textAlign }),
  setIconId: (iconId) => set({ iconId }),
  setIconLabel: (iconLabel) => set({ iconLabel }),
  setHllId: (hllId) => set({ hllId }),
  setHllShowRadius: (hllShowRadius) => set({ hllShowRadius }),
  setHllRadiusCheck: (hllRadiusCheck) => set({ hllRadiusCheck }),
  patch: (partial) => set(partial),
}));
