import { create } from "zustand";

export const useToolStore = create((set) => ({
  tool: "select",
  color: "#ffffff",
  strokeWidth: 3,
  lineType: "solid",
  endType: "none",
  startCap: "none",
  endCap: "none",
  opacity: 100,
  startSize: 5,
  endSize: 6,
  lineBezier: false,
  filled: true,
  fontSize: 14,
  textStyle: 0,
  textAlign: "center",
  fontFamily: "Inter",
  bold: false,
  italic: false,
  underline: false,
  textVAlign: "middle",
  outlineColor: "none",
  outlineWidth: 0,
  shadow: "none",
  padding: 2,
  rotation: 0,
  eyedropTarget: null,
  iconId: "check",
  iconLabel: "",
  hllId: "garrison",
  hllShowRadius: true,
  hllRadiusCheck: true,
  setTool: (tool) => set({ tool }),
  setColor: (color) => set({ color }),
  patch: (partial) => set(partial),
}));
