import vehiclesCatalog from "../../../../public/data/vehicles.json";

/**
 * Default transport-truck top speed (km/h) for route travel time.
 * Regenerated by `npm run extract:vehicles` from FModel blueprint exports (#26).
 */
export function getDefaultTransportSpeedKmh() {
  const id = vehiclesCatalog.defaultVehicleId || "transport-truck";
  const entry = vehiclesCatalog.vehicles?.[id] || vehiclesCatalog.vehicles?.["transport-truck"];
  const speed = entry?.maxSpeedKmh;
  if (typeof speed === "number" && speed > 0) return speed;
  return 38;
}

export function getVehicleEntry(vehicleId) {
  return vehiclesCatalog.vehicles?.[vehicleId] || null;
}

export { vehiclesCatalog };
